---
title: "Covariance Matrix - Prob 10.16"
author: "Blake Baird"
date: "2/17/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##  A is an n x k matrix.

```{r chnk1}
ones = function(n) matrix(rep(1,n)) # function to create a column vector of 1s
dat = cbind(c(2,5,6),c(8,22,8),c(9,10,11),c(22,44,66))
A = matrix(data=dat,ncol=4,nrow=3) # demonstration matrix
A
```

### a) Give expression for column mean (k-vector), $\mu$, in terms of A.

```{r chnk2}
n = nrow(A)
k = ncol(A)
one_over_n = matrix((1/n) * ones(n)) # scalar-vector multiplication
mu = crossprod(A, one_over_n)        # matrix-vector multiplication
one_over_n
mu  # vector of column means
```

### b) Give expression for de-meaned A, Atilde.

$\tilde{A} = A - 1_{n} \mu^T$

```{r chnk3}
Atilde = A - (ones(n) %*% t(mu))
Atilde # de-meaned A
```

### c) The *covariance matrix* $\Sigma = (1/N) \tilde{A}^{T}\tilde{A}$
The $\Sigma_{ii}$ terms are stdev($a_i$)$^2$ where $a_i$ are the column 
vectors of the original matrix, $A$.

The $\Sigma_{ij}$ terms are stdev($a_i$)stdev($a_j$)$\rho_{ij}$
where $\rho_{ij}$ is the correlation between columns i and j.
```{r chnk4}
library(magrittr) # import the pipe operator %>%

# stdev = rms of de-meaned vector
stdev = function(x) {
  if (!is.vector(x)) {
    warning("stdev should only be used on vectors")
    return(NULL)
  }
  sqrt( sum( (x - mean(x))^2 ) / length(x) )
}

covar = (1/n) * crossprod(Atilde)
covar

for(i in 1:4) stdev(A[,i])^2 %>% print
rho12 = covar[1,2] / ( diag(covar)[2]^0.5 * diag(covar)[1]^0.5 )
rho12
stdev(A[,1])*stdev(A[,2])*rho12
```